export const LOG_PROVIDER = 'LOG_PROVIDER';
export const LOG_CONFIG_PROVIDER = 'LOG_CONFIG_PROVIDER';
export const LOG_CONFIG_OPTIONS = 'LOG_CONFIG_OPTIONS';
export const LOG_CONFIG_KEY = 'log';
export const LOG_METADATA_CONFIG = 'LOG_METADATA_CONFIG';
export const LOG_METADATA = 'LOG_METADATA';
export const CONFIG = 'CONFIG';
